name: Lint Code

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20 # Встановлюємо версію Node.js
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Швидке встановлення з lock-файлу

      - name: Run ESLint
        run: npx eslint .